server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_mall_db?useUnicode=true&characterEncoding=UTF-8
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.my

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import:
      - application-oauth.yaml

# SSL setting

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: bootsecurity.p12
#    key-store-password: ${KEY_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: bootsecurity