#Oauth2 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9d1f6f0404717c12fd5a3ad686aa0b86
            client-secret: L77B2VvRYbddE8N4TUEMdSJUhEIWrii5
            redirect-uri: http://${SOCIAL_LOGIN_URL}:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
          naver:
            client-id: ihgnoPdKxVScMuGlDSLK
            client-secret: JampI300Ym
            redirect-uri: http://${SOCIAL_LOGIN_URL}:8080/oauth2/callback/naver
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

