spring:
  datasource:
    url: jdbc:mariadb://database-1.cxkkamogkg22.ap-northeast-2.rds.amazonaws.com:3306/super_mall_DB?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD_DEV}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    open-in-view: false
  config:
    activate:
      on-profile: dev
    import:
      - application-oauth.yaml

# SSL setting

server:
  ssl:
    key-store: keystore.p12
    key-password: ${KEY_PASSWORD}
    key-store-type: PKCS12
    key-alias: spring